package onboarding

// vocab is the pool of (sometimes serious, often silly) todos that drift across
// the onboarding background. Entries are unique and ASCII-only so the typewriter
// animation can reason about column widths one rune at a time. Keep it big and fun.
var vocab = []string{
	"Water the plants",
	"Call grandma",
	"Finally learn to juggle",
	"Buy oat milk",
	"Refactor the kitchen drawer",
	"Pet a dog",
	"Reply to that email from March",
	"Touch grass",
	"Plan the heist",
	"Name the houseplant",
	"Cancel the gym membership (again)",
	"Befriend the neighborhood crow",
	"Back up the laptop",
	"Floss, probably",
	"Read one more chapter",
	"Defeat the laundry mountain",
	"Schedule a dentist appointment",
	"Brew a better coffee",
	"Write the postcard",
	"Stretch for five minutes",
	"Update the resume",
	"Find the other sock",
	"Repot the basil",
	"Learn three chords",
	"Email past-me an apology",
	"Buy stamps like it's 1998",
	"Alphabetize the spice rack",
	"Take the scenic route",
	"Charge every device",
	"Whittle a tiny duck",
	"Return the library books",
	"Compliment a stranger",
	"Fix the wobbly table",
	"Start the sourdough",
	"Delete 4,000 photos",
	"Practice the elevator pitch",
	"Walk 10,000 steps",
	"Learn to say no",
	"Doodle in the margins",
	"Tip the barista extra",
	"Clean the keyboard crumbs",
	"Plan a tiny adventure",
	"Sort the cable drawer",
	"Sharpen the kitchen knives",
	"Rewatch a comfort movie",
	"Catalog the board games",
	"Donate the unworn shoes",
	"Learn a card trick",
	"Stargaze for an hour",
	"Send a thank-you note",
	"Mute the group chat",
	"Bake something ambitious",
	"Untangle the headphones",
	"Visit the farmers market",
	"Frame the good photo",
	"Try the scary recipe",
	"Learn everyone's birthday",
	"Oil the squeaky hinge",
	"Plant something edible",
	"Make the bed, victoriously",
	"Renew the passport",
	"Wash the reusable bags",
	"Pay it forward",
	"Memorize one good poem",
	"Set up the new router",
	"Vacuum under the couch",
	"Find a four-leaf clover",
	"Update the playlist",
	"Schedule a real vacation",
	"Practice patience in traffic",
	"Sort the junk drawer",
	"Learn the constellations",
	"Fix the broken zipper",
	"Test the smoke alarm",
	"Compose a haiku",
	"Drink some water already",
	"Organize the bookshelf",
	"Apologize to the printer",
	"Adopt a houseplant army",
	"Try a new lunch spot",
	"Learn to whistle properly",
	"Declutter the desktop",
	"Polish the good shoes",
	"Write down a dream",
	"Plan the surprise party",
	"Practice the high note",
	"Replace the toothbrush",
	"Build a blanket fort",
	"Take the stairs today",
	"Forgive the slow wifi",
	"Label the mystery cables",
	"Start the savings jar",
	"Learn one magic trick",
	"Wave at the mail carrier",
	"Repaint the fence",
	"Trim the bonsai",
	"Catch up on dishes",
	"Find the perfect mug",
	"Send a meme to a friend",
	"Reread the warranty",
	"Test the backup generator",
	"Sketch the skyline",
	"Master the perfect omelette",
	"Learn the neighbor's cat's name",
	"Plan a picnic",
	"Roll the spare change",
	"Update the emergency kit",
	"Practice gratitude",
	"Fix the leaky faucet",
	"Wind the old clock",
	"Discover a new podcast",
	"Tidy the garage corner",
	"Plant tulip bulbs",
	"Take a digital sunset",
	"Sort the recycling",
	"Learn semaphore, why not",
	"Befriend a sourdough starter",
	"Write a six-word story",
	"Replace the air filter",
	"Save the turtle screensaver",
	"Practice a brave hello",
	"Iron one nice shirt",
	"Find the missing puzzle piece",
	"Schedule the oil change",
	"Sweep the front porch",
	"Learn to fold a fitted sheet",
	"Re-pot the succulents",
	"Send a postcard from home",
	"Dust the top shelf",
	"Try left-handed handwriting",
	"Make a gratitude list",
	"Update the will, cheerfully",
	"Plan tomorrow tonight",
	"Reorganize the fridge",
	"Learn a tongue twister",
	"Fix the picture frame",
	"Try the unpronounceable tea",
	"Catalog the vinyl records",
	"Walk somewhere new",
	"Replace the lightbulb",
	"Write the elevator song",
	"Befriend the office plant",
	"Start a tiny garden",
	"Practice the firm handshake",
	"Archive the old projects",
	"Schedule a coffee with a friend",
	"Learn to skip a stone",
	"Conquer the inbox",
	"Sketch the morning light",
	"Free the trapped spider outside",
}
